kind: Service
apiVersion: v1
metadata:
  name: cr-controller
spec:
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
  selector:
    app: cr-controller
  type: ClusterIP
  sessionAffinity: None